<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 2016/9/30
 * Time: 上午12:46
 */

namespace backend\controllers;


use yii\data\ArrayDataProvider;
use yii\web\Controller;
use app\models\SmsAdmin;
use app\models\Teacher;
use app\models\VideoMaking;
use Yii;
use app\models\Project;
use yii\data\SqlDataProvider;
use yii\grid\GridView;
use app\models\ProjectSearch;

class PersonnelcountController extends Controller
{

    public function beforeAction($action)
    {
        if (empty(Yii::$app->user->identity)) {
            return $this->redirect(['/default/login']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {
        $firstday = strtotime(date('Y-m-01  ', time()));
        $lastday = strtotime(date('Y-m-31  ', time()));
        $db = Yii::$app->db;
        $model = new Project();
        $query = Yii::$app->request->queryParams;
        $sql_parms = ' and date between ' . $firstday . ' and ' . $lastday;
        $from_date = '';
        $to_date = '';
        if (!empty($query['Project'])) {
            $from_date = strtotime($query['Project']['from_date']);
            $to_date = strtotime($query['Project']['to_date']);
            $firstday = $from_date;
            $lastday = $to_date;
            $sql_parms = ' and a.date between ' . $from_date . ' and ' . $to_date;
        }
        //人员全部姓名
        $person_list = $db->createCommand("select name from sms_admin ")->queryAll();
        //人员课件表有课件存在时的姓名
        $person_filter = $db->createCommand("SELECT distinct a.makingname FROM courseware as a,project as b where a.pid =b.id  and date between " . $firstday . " and " . $lastday)->queryAll();
//        var_dump($person_filter);exit;
        //课件中存在的项目名
        $project_list = $db->createCommand("SELECT a.pid,b.projectname,b.is_neibu FROM courseware as a,project as b where a.pid =b.id  and date between " . $firstday . " and " . $lastday . " group by a.pid ")->queryAll();
        //获取筛选过的人员的项目统计结果
//        foreach ($person_filter as $k => $v) {
//            $sql = "SELECT a.makingname,count(a.id) as count_num, a.pid,b.projectname,b.is_neibu FROM courseware as a,project as b where a.pid =b.id and a.makingname = '" . $v['makingname'] . "'" . $sql_parms . " group by a.pid,a.makingname ";
//            $data = $db->createCommand($sql)->queryAll();
////            var_dump($sql);
//            print_r($data);
//            foreach ($data as $key => $value) {
//                $arr[] = [
//                    array(0 => $value['projectname']),
//                    array(1 => $value['makingname']),
//                    array(2 => $value['count_num']),
//                    array(3 => $value['is_neibu']),
//                    array(5 => $value['pid']),
//                ];
//            }
//        }
//        print_r($arr);exit;

        $test = $db->createCommand("select a.makingname, a.pid, count(makingname) as count_num, b.projectname  from courseware as a, project as b where date between " . $firstday . " and " . $lastday . " and a.pid = b.id group by a.pid,a.makingname")->queryAll();

//        print_r($test);exit;
//        foreach ($test as $item => $v) {
//            foreach ($v as $k =>$value) {
//                var_dump($k);exit;
//            }
//        }
//        var_dump(count($person_list));exit;

//        $tt = [];
//        $project_list = $db->createCommand("select id,projectname from project")->queryAll();
//        foreach ($project_list as $key => $value) {
//            print_r($value);
//            foreach ($person_list as $k => $v) {
//                print_r($v);exit;
//            }
//        }

//        $dataProvider = new ArrayDataProvider([
//            'allModels' => $test,
//            'pagination' => [
//                'pageSize' => 100,
//            ],
//            'sort' => [
//                'attributes' => ['id', 'name'],
//            ],
//        ]);
//
//        GridView::widget([
//            'dataProvider' => $dataProvider,
//        ]);

        return $this->render('index', [
            'model' => $model,
            'data' => $test,
//            'dataProvider' => $dataProvider,
            'project_list' => $project_list,
            'person_list' => $person_list,
            'query' => $query,
        ]);
    }
}