<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 2016/9/30
 * Time: 上午12:48
 */

namespace backend\controllers;

use app\models\SmsAdmin;
use app\models\Teacher;
use app\models\VideoMaking;
use Yii;
use app\models\Project;
use yii\data\ArrayDataProvider;
use yii\data\SqlDataProvider;
use yii\grid\GridView;
use app\models\ProjectSearch;
use yii\web\Controller;

class ProjectcountController extends Controller
{

    public function beforeAction($action)
    {
        if (empty(Yii::$app->user->identity)) {
            return $this->redirect(['/default/login']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $is_neibu = '';
        $is_neibu_total = '';
        $firstday = strtotime(date('Y-m-01  ', time()));
        $lastday = strtotime(date('Y-m-31  ', time()));
        $model = new Project();
        $db = Yii::$app->db;
        $query = Yii::$app->request->queryParams;
        $sql_parms = ' where time_int between ' . $firstday . ' and ' . $lastday;
        $sql_parms_2 = ' where date between ' . $firstday . ' and ' . $lastday;
        $from_date = '';
        $to_date = '';
        if (!empty($query['Project'])) {
            if (!empty($query['Project']['from_date'])) {
                if (!empty($query['Project']['to_date'])) {
                    $to_date = strtotime($query['Project']['to_date']);
                } else {
                    $to_date = $lastday;
                }
                $from_date = strtotime($query['Project']['from_date']);
//                $to_date = strtotime($query['Project']['to_date']);
                $firstday = $from_date;
                $lastday = $to_date;
                $sql_parms = ' where time_int between ' . $from_date . ' and ' . $to_date;
                $sql_parms_2 = ' where date between ' . $from_date . ' and ' . $to_date;
            }
            if (!empty($query['Project']['is_neibu'])) {
                if ($query['Project']['is_neibu'] == 2) {
                    $query['Project']['is_neibu'] = 0;
                }
                $is_neibu .= " where is_neibu = '" . $query['Project']['is_neibu'] . "'";
                $is_neibu_total = " and is_neibu = '" . $query['Project']['is_neibu'] . "'";
            }
        }
        //得到总计三个数据
        $record_time_total = $db->createCommand("SELECT sum(a.capture_time) as total_time  FROM video_shoot as a, project as b
where a.time_int between " . $firstday . " and " . $lastday . " and b.id = a.pid " .$is_neibu_total)->queryAll();

        $total_num_total = $db->createCommand("SELECT count(b.pid) as total_time  FROM courseware as b,project as a 
where date between " . $firstday . " and " . $lastday . " and a.id = b.pid " .$is_neibu_total)->queryAll();

        $video_time_total = $db->createCommand("SELECT sum(a.time) as total_time  FROM courseware as a,project as b
where a.date between " . $firstday . " and " . $lastday. " and b.id = a.pid " .$is_neibu_total)->queryAll();

        $sql_pro = "select id,projectname,school,is_neibu from project " . $is_neibu;
//        var_dump($sql_pro);
        $pro_data = $db->createCommand($sql_pro)->queryAll();
        //录制时长
        $video_data = $db->createCommand("select time_int,sum(capture_time) as record_time,pid from video_shoot " . $sql_parms . " GROUP BY pid")->queryAll();
        //课时总数和视频总时长
        $course_data = $db->createCommand("select date,count(*) as total_num, sum(time) as video_time,pid from courseware " . $sql_parms_2 . " group by pid")->queryAll();
        foreach ($video_data as $key => $value) {
            if (empty($value['record_time'])) {
                unset($video_data[$key]);
            }
        }
        foreach ($pro_data as $key => $value) {
            $pro_data[$key]['record_time'] = 0;
            $pro_data[$key]['total_num'] = 0;
            $pro_data[$key]['video_time'] = 0;
            $pro_data[$key]['from_date'] = $from_date;
            $pro_data[$key]['to_date'] = $to_date;
        }
        foreach ($pro_data as $key => $value) {
            foreach ($video_data as $k => $v) {
                if ($value['id'] == $v['pid']) {
                    $pro_data[$key]['record_time'] = $v['record_time'];
                }
            }
        }
        foreach ($pro_data as $key => $value) {
            foreach ($course_data as $k => $v) {
                if ($value['id'] == $v['pid']) {
                    $pro_data[$key]['total_num'] = $v['total_num'];
                    $pro_data[$key]['video_time'] = $v['video_time'];
                }
            }
        }

        foreach ($pro_data as $k => $v) {
            if ($v['record_time'] == 0 && $v['total_num'] == 0 && $v['video_time'] == 0) {
                unset($pro_data[$k]);
            }
        }
//        var_dump($pro_data);exit;

        $dataProvider = new ArrayDataProvider([
            'allModels' => $pro_data,
            'pagination' => [
                'pageSize' => 100,
            ],
            'sort' => [
                'attributes' => ['id', 'name'],
            ],
        ]);

        GridView::widget([
            'dataProvider' => $dataProvider,
        ]);

        return $this->render('index', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'record_time_total' => $record_time_total[0]['total_time'],
            'total_num_total' => $total_num_total[0]['total_time'],
            'video_time_total' => $video_time_total[0]['total_time'],
            'query' => $query,
            'from_date' => $from_date,
            'to_date' => $to_date,
        ]);
    }

    public function actionCoursesearch()
    {
        $firstday = strtotime(date('Y-m-01  ', time()));
        $lastday = strtotime(date('Y-m-31  ', time()));
        $model = new Project();
        $query = Yii::$app->request->queryParams;
        $from_date = $query[1]['from_date'];
        $to_date = $query[1]['to_date'];
        $pid = $query[1]['id'];
        $sql_params = " and b.date between " . $firstday . " and " . $lastday;
        if (!empty($query[1]['from_date'])) {
            $sql_params = " and b.date between " . $from_date . " and " . $to_date;
        }

        $sql = "select c.courcename, a.projectname,a.school,b.id,b.title,b.teacher,b.time,b.makingname,b.uploadname,b.state,b.date,b.enddate,b.totalday,b.remark
from project as a, courseware as b,video_making as c where b.pid = " . $pid . " and a.id = " . $pid . " and c.id = b.cid " . $sql_params;
//        var_dump($sql);exit;
        $command = Yii::$app->db->createCommand("select COUNT(b.id) from courseware as b where b.pid =" . $pid . $sql_params);
        $count = $command->queryScalar();

        $dataProvider = new SqlDataProvider([
            'sql' => $sql,
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 30,
            ],
            'sort' => [
                'attributes' => [
                    'id',
                ],
            ],
        ]);

        GridView::widget([
            'dataProvider' => $dataProvider,
        ]);

        return $this->render('coursesearch', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'query' => $query,
        ]);
    }

    public function actionVideosearch()
    {
        $firstday = strtotime(date('Y-m-01  ', time()));
        $lastday = strtotime(date('Y-m-31  ', time()));
        $model = new Project();
        $query = Yii::$app->request->queryParams;
        $pid = $query[1]['id'];
        $from_date = $query[1]['from_date'];
        $to_date = $query[1]['to_date'];
        $sql_params = " and b.time_int between " . $firstday . " and " . $lastday;

        if (!empty($query[1]['from_date'])) {
            $sql_params = " and b.time_int between " . $from_date . " and " . $to_date;
        }

//        $sql = "select * from video_shoot where pid =" . $pid . $sql_params;
        $sql = "select c.courcename, a.projectname,a.school,b.id,b.recordname,b.time,b.time_int,b.capture_time,b.uploadname,b.seat,b.teacher,b.status,b.remark
from project as a, video_shoot as b,video_making as c where b.pid = " . $pid . " and a.id = " . $pid . " and c.id = b.cid " . $sql_params;
        $command = Yii::$app->db->createCommand("select COUNT(b.id) from video_shoot as b where b.pid =" . $pid . $sql_params);
        $count = $command->queryScalar();

        $dataProvider = new SqlDataProvider([
            'sql' => $sql,
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 30,
            ],
            'sort' => [
                'attributes' => [
                    'id',
                ],
            ],
        ]);

        GridView::widget([
            'dataProvider' => $dataProvider,
        ]);

        return $this->render('videosearch', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'query' => $query,
        ]);
    }

}