<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "video_making".
 *
 * @property integer $id
 * @property string $makingname
 * @property integer $subtitle
 * @property string $projectname
 * @property string $school
 * @property string $courcename
 * @property integer $free
 * @property string $teacher
 * @property integer $pid
 */
class VideoMaking extends \yii\db\ActiveRecord
{
    public $imageFiles;
    private $pic_name;
    private $path;
    private $time;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'video_making';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
//            [['id'], 'required'],
            [['id', 'subtitle', 'free', 'status', 'pid'], 'integer'],
            [['makingname', 'projectname', 'teacher', 'school', 'courcename'], 'string', 'max' => 100],
            [['teacher'], 'string', 'max' => 50],
//            [['pic'], 'file','maxFiles' => 14],
            [['imageFiles'], 'file', 'maxFiles' => 14],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'makingname' => '上传人',
            'subtitle' => '字幕',
            'projectname' => '项目名',
            'school' => '学校',
            'courcename' => '课程名',
            'free' => '结算',
            'teacher' => '讲师',
            'status' => '审核',
            'pid' => 'Pid',
            'imageFiles' => '图片',
        ];
    }

    public function upload()
    {
        if ($this->validate()) {
            foreach ($this->imageFiles as $k => $v) {
                $pic_name = $v->name;
                $this->pic_name = $v->name;
                $type = strpos($pic_name, '.jpg') === false ? '.png' : '.jpg';
                $this->path = 'upload_files\pic\\' . date("Y-m-d-") . time() . '_' . $k . $type ;
                $v->saveAs(dirname(__DIR__) . '\\web\\' . $this->path;
            }
            return true;
        } else {
            return false;
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $cid = $this->id;
        foreach ($this->imageFiles as $k => $v) {
            $pic_model = new Pic();
            $pic_name = $v->name;
            $this->pic_name = $v->name;
            $type = strpos($pic_name, '.jpg') === false ? '.png' : '.jpg';
            $path = 'upload_files\pic\\' . date("Y-m-d-") . time() . '_' . $k . $type ;
            $pic_model->setAttributes([
                'type' => 0,
                'name' => $pic_name,
                'path' => $path,
                'cid' => $cid,
            ]);
            $pic_model->save();
            var_dump($k);
        }
    }


    public function getCourseList()
    {
        $list = self::findBySql('select DISTINCT courcename,id from video_making')->all();
        $course_list = [];
        foreach ($list as $k => $v) {
            $key = $v['courcename'];
            $course_list[$key] = $v['courcename'];
        }
        return $course_list;
    }

}
