<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "video_shoot".
 *
 * @property integer $id
 * @property string $recordname
 * @property string $time
 * @property string $time1
 * @property double $capture_time
 * @property string $uploadname
 * @property integer $seat
 * @property string $projectname
 * @property string $school
 * @property string $courcename
 * @property string $teacher
 * @property string $status
 * @property string $auditor1
 * @property string $auditor2
 * @property integer $cid
 */
class VideoShoot extends \yii\db\ActiveRecord
{
    public $imageFiles;
    private $pic_name;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'video_shoot';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['time1'], 'required'],
            [['capture_time'], 'number'],
            [['seat', 'cid'], 'integer'],
            [['recordname', 'time', 'time1', 'uploadname', 'projectname', 'school', 'courcename', 'teacher', 'status', 'auditor1', 'auditor2'], 'string', 'max' => 100],
            [['imageFiles'], 'file', 'maxFiles' => 14],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'recordname' => '录制人',
            'time' => '拍摄时间',
            'time1' => '拍摄时间1',
            'capture_time' => '时长',
            'uploadname' => '上传人',
            'seat' => '机位个数',
            'projectname' => '项目名称',
            'school' => '学校',
            'courcename' => '课程名称',
            'teacher' => '主讲人',
            'status' => '审核',
            'auditor1' => 'Auditor1',
            'auditor2' => 'Auditor2',
            'cid' => 'Cid',
            'imageFiles' => '图片',
        ];
    }

    // videomaking 表存入数据后 把图片存入pic表
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $cid = $this->id;

        if ($this->imageFiles) {
            foreach ($this->imageFiles as $k => $v) {
                $pic_model = new Pic();
                $pic_name = $v->name;
                $this->pic_name = $v->name;
                $type = strpos($pic_name, '.jpg') === false ? '.png' : '.jpg';
                $path = 'upload_files\pic\\' . date("Y-m-d-H-i-s") . '_' . $k . $type ;
                $pic_model->setAttributes([
                    'type' => 0,
                    'name' => $pic_name,
                    'path' => $path,
                    'cid' => $cid,
                ]);
                $pic_model->save();
                $v->saveAs(dirname(__DIR__) . '\\web\\' . $path);
            }
        }
    }
}
